name: Final_project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run custom script
        env:
         NUM: ${{ secrets.WEBSITE_ADDRESS }}
        run: sh Scripts/status_code_script.sh
        
  run_postman:
    runs-on: ubuntu-latest
    needs:
    - run_script

    steps:
      - uses: actions/checkout@v3
      
      - name: Node.js install
        uses: actions/setup-node@v3
        with:
         node-version: '20'

      - name: Newman install
        run: npm install -g newman

      - name: Run Postman collection
        run: newman run Postman/Petstore.postman_collection.json -e Postman/Petstore_Environment.postman_environment.json
